---
- name: Simple connectivity test
  hosts: all
  gather_facts: false

  tasks:
    - name: Show hostname
      ansible.builtin.command: hostname
      register: host

    - name: Print hello message
      ansible.builtin.debug:
        msg: "Hello from {{ host.stdout }}"
